### ISSUE TITLE
隐藏发送请求的section

### ISSUE THREAD

**Issue by yinshangwei** [ZhangYuanSheng1217/RestfulTool#10]
![image](https://user-images.githubusercontent.com/20291587/83606881-ded9e000-a5ac-11ea-86ef-de33e472bf4e.png)
发送请求的这一块，既不能拖动也无法隐藏，笔记本电脑屏幕本来就小，这一块占了很多地方，能不能加个功能能让这块不显示，很多时候我只想查找api list，并不需要发送请求。

**Comment by ZhangYuanSheng1217** [comment]
已经加上了哈，你可以直接下载根目录的压缩包安装，审核上线就没那么快
