### ISSUE TITLE
RequestBody的内容出问题

### ISSUE THREAD

**Issue by CarlosShao** [ZhangYuanSheng1217/RestfulTool#11]
在postman里面都可以正常显示,  但是在插件里面body填写参数就报requestbody的参数问题, 麻烦作者告诉我该怎么填, 谢了大佬

**Comment by ZhangYuanSheng1217** [comment]
默认是
`key1: value2`
`key2: value2`
如果还是不行的话麻烦给我看一下你的方法参数吧(˶˚  ᗨ ˚˶)

**Comment by CarlosShao** [comment]
> 默认是
> `key1: value2`
> `key2: value2`
> 如果还是不行的话麻烦给我看一下你的方法参数吧(˶˚ ᗨ ˚˶)

![image](https://user-images.githubusercontent.com/35945730/83762167-d0252300-a6a9-11ea-8cef-37653cf0850b.png)
![image](https://user-images.githubusercontent.com/35945730/83762225-e337f300-a6a9-11ea-8a77-8c430ce397b8.png)
实际上我前台只传了一个值过来了, 就是01

**Comment by CarlosShao** [comment]
我用idea自带的Rest Client测试如下
![image](https://user-images.githubusercontent.com/35945730/83762569-41fd6c80-a6aa-11ea-9750-94ffdd659657.png)
![image](https://user-images.githubusercontent.com/35945730/83762619-4f1a5b80-a6aa-11ea-93c6-6306691ac044.png)

**Comment by CarlosShao** [comment]
其实我就是想问问作者大大, requestbody的参数我怎么填呢,类似这种raw-body的传参

**Comment by ZhangYuanSheng1217** [comment]
懂了，因为你加了@RequestBody，所以用的是application/json格式，这个功能我还没加上

**Comment by CarlosShao** [comment]
啊,这...没事我会继续支持大佬的, 因为另一款我也用不了, 不支持2020版本的idea, 但是我就是喜欢2020的启动画面,2333

**Comment by ZhangYuanSheng1217** [comment]
感谢哈，不过2020确实好看

**Comment by CarlosShao** [comment]
> 感谢哈，不过2020确实好看

老哥, 你要是不介意的话, 就这个插件我提几点建议

**Comment by ZhangYuanSheng1217** [comment]
随便提，欢迎哈

**Comment by CarlosShao** [comment]
> 随便提，欢迎哈

emmm, 作为一个白嫖党有点嚣张了..
1. 就是我刚说的可以考虑支持一下requestBody参数类型的请求
2. 我觉得url这个不大方便, 因为我点击另外一个请求地址的时候, 前面的端口号和项目名字就会被刷掉了,这样每个url的测试就会比较麻烦;我看到其实都已经能够显示模块名了, 所以建议模块名可以加在url上面, 端口的话就有点难了...
![image](https://user-images.githubusercontent.com/35945730/83765237-82aab500-a6ad-11ea-89ae-2e2de3118be4.png)
3. 这里好像有点bug
![image](https://user-images.githubusercontent.com/35945730/83765566-eaf99680-a6ad-11ea-9644-6e124057eb71.png)我在往左边拉的时候, 这一块会往下面塌, 然后再往右拖就上去了

**Comment by CarlosShao** [comment]
> 随便提，欢迎哈

其实是不影响基础功能使用的, 但是, 我想抛弃开另一个rest的测试插件或者打开postman了, 老卡了...

**Comment by ZhangYuanSheng1217** [comment]
确实，能在一个程序做的东西我都不想再开一个程序

**Comment by CarlosShao** [comment]
> 确实，能在一个程序做的东西我都不想再开一个程序

其实大佬你可以做的成熟一点, 取代那个RestfulToolKit, 就算是收费其实也还行, 类似Mybatis Log那个, 也是有很多人花钱的

**Comment by ZhangYuanSheng1217** [comment]
这个其实没必要哈，赞助是可以，收钱就没意思了，而且用的人多了其实也是种支持(*￣︶￣)
另外你那个第二条可以详细说下嘛，我没看明白

**Comment by CarlosShao** [comment]
> 这个其实没必要哈，赞助是可以，收钱就没意思了，而且用的人多了其实也是种支持(*￣︶￣)
> 另外你那个第二条可以详细说下嘛，我没看明白

好的, 我意思就是, url那里可以把模块名加上, 默认是http://localhost:8080/url
我所想的是: localhost:8080/projectName/url
还有就是点别的url的时候, 希望前面部分不要刷新才好

**Comment by CarlosShao** [comment]
> 咱俩私聊吧，这里有点不太好沟通

好的, 大佬我vx: a933942520

**Comment by ZhangYuanSheng1217** [comment]
加你了
