### ISSUE TITLE
RestServices windows is showing in blank

### ISSUE THREAD

**Issue by jeremylima** [ZhangYuanSheng1217/RestfulTool#13]
**Describe the bug**
After update IntelliJ to the latest version 2020.1.2 Ultimate Edition, the RestServices window doesn't  work. It shows empty.

**To Reproduce**
1. Update IntelliJ to 2020.1.2 Ultimate Edition
2. Go to 'RestServices tab'
3. See it empty.

**Expected behavior**
Here the list of endpoints were showing properly, and you can navigate between them.

**Screenshots**
![Screenshot from 2020-06-08 23-10-58](https://user-images.githubusercontent.com/12650938/84109129-3201c780-a9df-11ea-9936-36ad1240680e.png)

**Desktop:**
 - OS: Ubuntu

**Additional notes**
The rest of functionalities works fine, only the RestServices windows doesn't.

**Comment by ZhangYuanSheng1217** [comment]
The pulgin'name is RestfulTool
