### ISSUE TITLE
接口上的请求无法解析

### ISSUE THREAD

**Issue by sj13824803000** [ZhangYuanSheng1217/RestfulTool#15]
我是微服务的项目,然后为了方便各个项目之间的接口依赖,我会把服务的接口,先用interface定义,然后再写controller实现该接口.  目前发现该类型的controller工具不支持
## interface如下
![image](https://user-images.githubusercontent.com/24707427/84217639-4210c880-aaff-11ea-9e08-3b872e36f570.png)
## controller如下
![image](https://user-images.githubusercontent.com/24707427/84217674-5ce33d00-aaff-11ea-8f79-546bef69119c.png)

**Comment by ZhangYuanSheng1217** [comment]
请问方便帮忙测试一下吗？

**Comment by sj13824803000** [comment]
> 请问方便帮忙测试一下吗？

可以的,怎么测插件? 你给我发一个包吗

**Comment by ZhangYuanSheng1217** [comment]
> > 请问方便帮忙测试一下吗？
> 
> 可以的,怎么测插件? 你给我发一个包吗

我发你邮箱，或者我发布一个release，可以吗？

**Comment by sj13824803000** [comment]
> > > 请问方便帮忙测试一下吗？
> > 
> > 
> > 可以的,怎么测插件? 你给我发一个包吗
> 
> 我发你邮箱，或者我发布一个release，可以吗？

发邮箱吧 sj13824803000@hotmail.com    测试没问题再发布release好点

**Comment by ZhangYuanSheng1217** [comment]
你好，已经发过去了

**Comment by sj13824803000** [comment]
> 你好，已经发过去了

赞!!!没问题.你可以发布release了

**Comment by ZhangYuanSheng1217** [comment]
多谢帮忙测试(*￣︶￣)
