### ISSUE TITLE
希望在生成json的时候可以将类中父类的参数添加上去

### ISSUE THREAD

**Issue by yujiancheng** [ZhangYuanSheng1217/RestfulTool#16]
如题

**Comment by ZhangYuanSheng1217** [comment]
不太明白，能举个例子吗

**Comment by yujiancheng** [comment]
抱歉，我这邮件没有及时看到，是这样例如说我请求一个接口，参数是

student：｛
“grade”:2,
“no:”:1001
｝

他有一个父类：
Person：｛
“name”: xiaoming,
Sex: 男
｝

实际，我的参数是
student：｛
“name”: xiaoming,
Sex: 男
“grade”:2,
“no:”:1001
｝

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yuonsa<mailto:notifications@github.com>
发送时间: 2020年6月16日 2:03
收件人: ZhangYuanSheng1217/RestfulTool<mailto:RestfulTool@noreply.github.com>
抄送: yujiancheng<mailto:yujiancheng@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ZhangYuanSheng1217/RestfulTool] 希望在生成json的时候可以将类中父类的参数添加上去 (#16)


不太明白，能举个例子吗

―

**Comment by ZhangYuanSheng1217** [comment]
已解决
