### ISSUE TITLE
Show all Restful API in current class, like structure

### ISSUE THREAD

**Issue by leeychee** [ZhangYuanSheng1217/RestfulTool#19]
In some projects, there are lots of RESTful API in one module. If I want to check RESTful in one class (like a controller), It's not very convenient.

So, Could I just list all RESTful API in the current class in RESTful Toolkit window?

**Comment by ZhangYuanSheng1217** [comment]
已经完成了，请前往 [下载](https://github.com/ZhangYuanSheng1217/RestfulTool/releases/tag/1.2.3.1-RELEASE) 安装

**Comment by leeychee** [comment]
Thank you for the new feature. But current implementation seems a little wired.

**Comment by ZhangYuanSheng1217** [comment]
Thanks. Can you elaborate on that?



---Original---

**Comment by leeychee** [comment]
I have updated the comment, please recheck.

**Comment by ZhangYuanSheng1217** [comment]
Because the way you say it is not easy to interact.
