### ISSUE TITLE
如果requestMapping类上末尾加了/，方法开头也带/则无法被扫描到

### ISSUE THREAD

**Issue by fzustone** [ZhangYuanSheng1217/RestfulTool#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
当在类级别的@RequestMapping("/index/"),在方法上的@RequestMapping("/test/user"),那么插件将无法扫描到/index/test/user,但实际上Spring是允许这么使用，且调用也是没问题，希望能支持这种情况的路径扫描
**Describe alternatives you've considered**

**Additional context**

**Comment by ZhangYuanSheng1217** [comment]
方便给我看看是哪个方法没被扫描到吗？

**Comment by MoneZhao** [comment]
比如这种就无法扫描到
```java
@RequestMapping("/actuator/")
public class MonitorController {
    @GetMapping("/redis/info")
    public Result getRedisInfo() throws Exception {
        List<RedisInfo> infoList = this.redisService.getInfo();
        return Result.ok(infoList);
    }
}
```

**Comment by tian2928** [comment]
> 比如这种就无法扫描到
> 
> ```java
> @RequestMapping("/actuator/")
> public class MonitorController {
>     @GetMapping("/redis/info")
>     public Result getRedisInfo() throws Exception {
>         List<RedisInfo> infoList = this.redisService.getInfo();
>         return Result.ok(infoList);
>     }
> }
> ```

测试了一下，确实是。RequestMapping上最后如果有“/”就扫描不到
![image](https://user-images.githubusercontent.com/31798034/85200566-22fa0e00-b32b-11ea-963e-7837486b6d9c.png)
![image](https://user-images.githubusercontent.com/31798034/85200581-4329cd00-b32b-11ea-9626-e9b40e414b31.png)

**Comment by ZhangYuanSheng1217** [comment]
明白了，谢谢您的反馈



---原始邮件---
发件人: "田正相"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 晚上7:22
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 如果requestMapping类上末尾加了/，方法开头也带/则无法被扫描到 (#20)




  
比如这种就无法扫描到
 @RequestMapping("/actuator/") public class MonitorController {     @GetMapping("/redis/info")     public Result getRedisInfo() throws Exception {         List<RedisInfo&gt; infoList = this.redisService.getInfo();         return Result.ok(infoList);     } }
  
测试了一下，确实是。RequestMapping上最后如果有“/”就扫描不到

**Comment by ZhangYuanSheng1217** [comment]
已经解决，暂时先下载zip包本地安装吧



---原始邮件---
发件人: "田正相"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 晚上7:22
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 如果requestMapping类上末尾加了/，方法开头也带/则无法被扫描到 (#20)




  
比如这种就无法扫描到
 @RequestMapping("/actuator/") public class MonitorController {     @GetMapping("/redis/info")     public Result getRedisInfo() throws Exception {         List<RedisInfo&gt; infoList = this.redisService.getInfo();         return Result.ok(infoList);     } }
  
测试了一下，确实是。RequestMapping上最后如果有“/”就扫描不到
