### ISSUE TITLE
暗黑主题适配不太好

### ISSUE THREAD

**Issue by 919493002** [ZhangYuanSheng1217/RestfulTool#21]
![Snipaste_2020-06-18_13-11-37](https://user-images.githubusercontent.com/48093096/84980704-5428e180-b165-11ea-8cba-7fe6b5a9edb5.png)

**Comment by MoneZhao** [comment]
先把 color schema改成其他的，再改回来，就可以了

**Comment by ZhangYuanSheng1217** [comment]
已修复
