### ISSUE TITLE
最新版IDEA 2020.01版本看不到接口列表

### ISSUE THREAD

**Issue by EnjoywithSunshine** [ZhangYuanSheng1217/RestfulTool#25]
多模块项目，用ctrl  \ 能找到方法映射路径，但是插件面板上是一片空白，是新版的IDEA有什么变动，得你们去做适应吗？

![图片](https://user-images.githubusercontent.com/31517677/85193265-72274b00-b2f9-11ea-9f50-03b9e668b866.png)
![图片](https://user-images.githubusercontent.com/31517677/85193281-8ec38300-b2f9-11ea-9435-16acc3940ccf.png)

**Comment by ZhangYuanSheng1217** [comment]
你装的是哪个插件？
[RestfulTool](https://plugins.jetbrains.com/plugin/14280-restfultool) 才是我针对201版本以上制作的

**Comment by EnjoywithSunshine** [comment]
谢谢，我装的是 RestfulToolkit 难怪不行，哈哈哈哈，不好意思大佬，打搅了，一切正常
