### ISSUE TITLE
不能识别配置文件的端口号吗

### ISSUE THREAD

**Issue by hangzhouljp** [ZhangYuanSheng1217/RestfulTool#28]
http://localhost:8080/home/selectStock
路径也不能识别
server:
  port: 16001 #启动端口

**Comment by ZhangYuanSheng1217** [comment]
项目结构看看，还有端口配置

**Comment by hangzhouljp** [comment]
直接从插件中心下载的 
![image](https://user-images.githubusercontent.com/38392441/86903118-7baa1300-c141-11ea-8168-2e4af65b8fdc.png)
![image](https://user-images.githubusercontent.com/38392441/86903152-85cc1180-c141-11ea-8532-9961de1c4951.png)

**Comment by hangzhouljp** [comment]
你不能识别application.yml里的端口号和路径 1.2.0版本及以上都有这个问题

**Comment by ZhangYuanSheng1217** [comment]
逻辑问题，正在修复

**Comment by hangzhouljp** [comment]
![image](https://user-images.githubusercontent.com/38392441/86907161-34bf1c00-c147-11ea-9a83-b0413e65093f.png)
实体类里有list对象不能识别
![image](https://user-images.githubusercontent.com/38392441/86907221-4c96a000-c147-11ea-8da5-0bc2b75f57e7.png)

**Comment by ZhangYuanSheng1217** [comment]
做了只识别.java

**Comment by hangzhouljp** [comment]
不太懂 能详细说一下吗

**Comment by ZhangYuanSheng1217** [comment]
晚点吧，先把端口扫描的逻辑优化了

**Comment by hangzhouljp** [comment]
我下载源码学习学习

**Comment by ZhangYuanSheng1217** [comment]
已经OK了，你下载本地安装吧
