### ISSUE TITLE
Will be posted to Jetbrains Plugins ?

### ISSUE THREAD

**Issue by jlfsdtc** [ZhangYuanSheng1217/RestfulTool#3]
It's a great plugins.
If posted to Jetbrains Plugins ,use much easier.

**Comment by ZhangYuanSheng1217** [comment]
Thank you, but the plugin has been released, address: https://plugins.jetbrains.com/plugin/14280-restfultool

**Comment by mystic-cg** [comment]
Intellij IDEA Community cannot find this plugin. Do you release it to the community version?

**Comment by ZhangYuanSheng1217** [comment]
Thank you very much for your valuable comments, and I will support the community version IDE in subsequent development！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mystic"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 上午10:52
收件人:&nbsp;"ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送:&nbsp;"　"<2862297923@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangYuanSheng1217/RestfulTool] Will be posted to Jetbrains Plugins ? (#3)





 
Intellij IDEA Community cannot find this plugin. Do you release it to the community version?
