### ISSUE TITLE
path on Class 类上的路径被忽略了

### ISSUE THREAD

**Issue by habyss** [ZhangYuanSheng1217/RestfulTool#31]
```
@RestController
@RequestMapping("/order")
public class OrderController {
   
    @RequestMapping(value = "/updateTransByCode")
    public StringupdateTransByCode(){
        return "succ";
    }
}
```
no path "order":
RestfulTool界面工具没有路径"order"
![no path "order"](https://user-images.githubusercontent.com/45258883/87263257-32feab00-c4ef-11ea-89c4-23bfd8bbd565.png)
no path "order":
搜索结果没有路径"order"
![image](https://user-images.githubusercontent.com/45258883/87263331-62adb300-c4ef-11ea-82e0-95d969861855.png)

**Comment by ZhangYuanSheng1217** [comment]
请先升级到最新版本再试试吧

**Comment by habyss** [comment]
这是我的版本, 应该是最新的:
![image](https://user-images.githubusercontent.com/45258883/87279811-fac58f80-c523-11ea-9e87-350876d49101.png)
这是我有疑惑的地方:
![image](https://user-images.githubusercontent.com/45258883/87280123-5d1e9000-c524-11ea-9066-289ca690584f.png)

**Comment by ZhangYuanSheng1217** [comment]
应该是插件库没更新，你可以卸载了重新安装试下
