### ISSUE TITLE
自定义Mapping无法扫描

### ISSUE THREAD

**Issue by zhangjp9510** [ZhangYuanSheng1217/RestfulTool#32]
想要参考PostMapping，自行定义一个新的Mapping 注解。
但是组件无法找到该Mapping

这个功能有解决方案吗？

**Comment by ZhangYuanSheng1217** [comment]
如果跟@PostMapping类似
 - clone项目到本地
 - 修改 `com.github.restful.tool.annotation.SpringHttpMethodAnnotation`，增加自定义的Mapping
- 
![image](https://user-images.githubusercontent.com/21291815/88206094-58727e00-cc80-11ea-998c-f55cdb5069ea.png)
