### ISSUE TITLE
能不能在设置中增加一下模块默认展开还是收起

### ISSUE THREAD

**Issue by MoneZhao** [ZhangYuanSheng1217/RestfulTool#36]
![image](https://user-images.githubusercontent.com/20487270/88629838-5aa26580-d0e2-11ea-90a4-dab4485315fd.png)

建议在设置中增加选项可以设置默认展开还是收起，对于多模块的项目比较友好

**Comment by ZhangYuanSheng1217** [comment]
你的意思是单个模块的展开或者收起吗

**Comment by MoneZhao** [comment]
> 你的意思是单个模块的展开或者收起吗

不是，所有模块的统一的，我记得restfultoolkit默认就收起的

**Comment by ZhangYuanSheng1217** [comment]
![image](https://user-images.githubusercontent.com/21291815/88647670-d0b1c700-d0f8-11ea-8adf-a08d19561623.png)
你把这个注释掉就OK，或者参数直接写false

**Comment by MoneZhao** [comment]
我自己打包吗？要不我改好了之后，发一个pr？

**Comment by ZhangYuanSheng1217** [comment]
你可以自己打包了先用着，增加设置这个要等下个版本一起上

**Comment by MoneZhao** [comment]
OK

**Comment by ZhangYuanSheng1217** [comment]
或者我加了设置之后打包发你一份

**Comment by MoneZhao** [comment]
不用麻烦了，我自己打包好了😀

**Comment by ZhangYuanSheng1217** [comment]
你那个不是没加设置吗

**Comment by MoneZhao** [comment]
我直接折叠就好了，不用设置，只是觉得你可以下一次打包有个设置会人性化一点

**Comment by ZhangYuanSheng1217** [comment]
那行

**Comment by ZhangYuanSheng1217** [comment]
我已经改好了，在dev，你要是要设置的话直接编译打包就行

**Comment by MoneZhao** [comment]
鬼鬼，你这也太神速了，那可以close了

**Comment by ZhangYuanSheng1217** [comment]
主要还是不麻烦，加上当初搭的架子基本还行
