### ISSUE TITLE
生成JSON时可否解析下@JsonProperty注解

### ISSUE THREAD

**Issue by zztriana** [ZhangYuanSheng1217/RestfulTool#40]
代码使用了@JsonProperty注解来将序列化参数，插件现在是直接读取的变量名称。
请求加入优先解析@JsonProperty注解定义值的逻辑😊

**Comment by spinachomes** [comment]
这种功能怕是自己加比较好，不通用啊。只适合使用jackson的人

**Comment by zztriana** [comment]
> 这种功能怕是自己加比较好，不通用啊。只适合使用jackson的人

是的..我已经自己加上了。
顺便提个小建议，默认的请求10s超时可以开放出来供配置。毕竟有时候需要debug，断点一打就不止10s了
