### ISSUE TITLE
接口上添加的 Spring Web 相关注解无法识别

### ISSUE THREAD

**Issue by zzuhkp** [ZhangYuanSheng1217/RestfulTool#41]
使用 @RequestMapping 自定义类似 @PostMapping 之类的注解添加在 Spring Bean 所实现的接口上时无法识别，能否加以支持？
Spring 中可以通过RequestMapping requestMapping = AnnotatedElementUtils.findMergedAnnotation(method, RequestMapping.class); 从自定义的注解中获取指定注解

**Comment by ZhangYuanSheng1217** [comment]
？

**Comment by zzuhkp** [comment]
不好意思，可能我没有表达清楚。
1、我现在的场景和 https://github.com/ZhangYuanSheng1217/RestfulTool/issues/15 一致。
2、我遇到问题和 https://github.com/ZhangYuanSheng1217/RestfulTool/issues/32 一致。

我是把自定义的注解 Mapping 注解 加在了接口上，无法识别。

自定义注解如下：
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@RequestMapping(method = RequestMethod.POST)
public @interface JsonPostMapping {

    ... 省略部分代码

    /**
     * Alias for {@link RequestMapping#consumes}.
     */
    @AliasFor(annotation = RequestMapping.class)
    String[] consumes() default {MediaType.APPLICATION_JSON_VALUE};

    /**
     * Alias for {@link RequestMapping#produces}.
     */
    @AliasFor(annotation = RequestMapping.class)
    String[] produces() default {MediaType.APPLICATION_JSON_VALUE};

}

使用方式如下：
@RestController
@JsonPostMapping("/channel-code")
public interface ChannelCodeService {

    @JsonPostMapping(value = "/add")
    CommonResponse<Integer> addChannelCode(@RequestBody @Valid ChannelCodeAddDTO addDTO);

}

@Service
public class ChannelCodeServiceImpl implements ChannelCodeService {

    @Override
    public CommonResponse<Integer> addChannelCode(@Valid ChannelCodeAddDTO addDTO) {
        ... 省略部分代码
    }
}

未识别出接口 /channel-code/add

**Comment by ZhangYuanSheng1217** [comment]
搞定了，下个版本增加
