### ISSUE TITLE
default server port and request headers configuration template needed

### ISSUE THREAD

**Issue by fudax** [ZhangYuanSheng1217/RestfulTool#42]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
设置中最好能够支持配置服务默认端口号，多服务开发时并不总是localhost:8080
设置中最好能够支持配置默认的请求头，这样不用每个请求都去配置一遍

**Describe alternatives you've considered**

**Additional context**

**Comment by ZhangYuanSheng1217** [comment]
端口通过配置文件扫描，没扫描到才是默认8080

**Comment by fudax** [comment]
现在很多端口配置都丢到配置中心去了，就看下能否支持设置

**Comment by ZhangYuanSheng1217** [comment]
由于网络原因暂时不考虑配置中心哈

**Comment by m00119022** [comment]
> 端口通过配置文件扫描，没扫描到才是默认8080

yml和properties都可以吗？测试了一下：单配置也不行。。
