### ISSUE TITLE
mac系统下，打开搜索框的快捷键是什么

### ISSUE THREAD

**Issue by zhangchunxing** [ZhangYuanSheng1217/RestfulTool#43]

**Comment by ZhangYuanSheng1217** [comment]
这我还真不知道，你可以自己去设置里面找到RestfulTool，然后自己设置mac对应的快捷键

**Comment by zhangchunxing** [comment]
...尴尬

**Comment by ZhangYuanSheng1217** [comment]
![image](https://user-images.githubusercontent.com/21291815/90333191-605edd00-dff6-11ea-9982-10dea5167a38.png)
