### ISSUE TITLE
映射问题

### ISSUE THREAD

**Issue by nichuanfang** [ZhangYuanSheng1217/RestfulTool#45]
**springboot项目映射问题**
1.映射有缺少的选项
2.RestfulTree可以搜索到相应的api 希望能添加快捷跳转 支持api演示

**Comment by ZhangYuanSheng1217** [comment]
第一点的话具体点才知道
第二点：支持双击跳转到对应方法，api演示的话没明白啥意思

**Comment by nichuanfang** [comment]
已解决. idea原生支持聚焦事件搜索,快捷跳转也看到了.谢谢大佬

**Comment by ZhangYuanSheng1217** [comment]
客气了
