### ISSUE TITLE
提供对 Kotlin 的支持

### ISSUE THREAD

**Issue by kbyyd24** [ZhangYuanSheng1217/RestfulTool#47]
以前的那个插件是支持 Kotlin 的，现在这个插件看起来只支持 Java。有没有可能加入对 Kotlin 的支持呢？

**Comment by ZhangYuanSheng1217** [comment]
已经加了，预览版试试吧

**Comment by kbyyd24** [comment]
预览版怎么安装呢？没找到安装的方式

**Comment by ZhangYuanSheng1217** [comment]
https://github.com/ZhangYuanSheng1217/RestfulTool/releases/tag/1.2.8
下载本地安装就行

**Comment by kbyyd24** [comment]
可以了，多谢 👍

**Comment by ZhangYuanSheng1217** [comment]
增加了基本参数解析，烦请方便的时候试试


https://github.com/ZhangYuanSheng1217/RestfulTool/releases/tag/1.2.8.109



打扰了



---原始邮件---
发件人: "Yuexiang Gao"<notifications@github.com&gt;
发送时间: 2020年9月9日(周三) 上午9:20
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 提供对 Kotlin 的支持 (#47)




 
可以了，多谢 👍

**Comment by kbyyd24** [comment]
有点问题，controller 的参数都被放到一个 json object 里了，并且 request body 没有解析，识别成了一个字符串

**Comment by ZhangYuanSheng1217** [comment]
具体看看



---原始邮件---
发件人: "Yuexiang Gao"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 中午1:35
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 提供对 Kotlin 的支持 (#47)




 
有点问题，controller 的参数都被放到一个 json object 里了，并且 request body 没有解析，识别成了一个字符串

**Comment by kbyyd24** [comment]
不好意思才看到，大概是这样的代码

```kotlin
@RestController
class Controller() {
  @PutMapping("{id}")
  fun doSomething(@PathVariable id: String, @RequestBody command: Command) = //...
}

data class Command(
  val field1: String,
  // ...
)
```

Sidebar 里面看到识别到的 request body 成了：

```json
{
  "id": "",
  "command": ""
}
```

对于有 response body 的 API，识别到的 response 也是空的。
我们的 command  和 resopnse 都是用的 data class，controller 上的方法都是使用的表达式，没有写返回类型。

**Comment by ZhangYuanSheng1217** [comment]
哦哦，原来是这样，不过我kotlin还不太熟，暂时没法解决这个，抱歉了


---原始邮件---
发件人: &quot;Yuexiang Gao&quot;<notifications@github.com&gt;
发送时间: 2020年9月30日(周三) 晚上10:36
收件人: &quot;ZhangYuanSheng1217/RestfulTool&quot;<RestfulTool@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;Yuonsa&quot;<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 提供对 Kotlin 的支持 (#47)




 
不好意思才看到，大概是这样的代码
 @RestController class Controller() {   @PutMapping("{id}")   fun doSomething(@PathVariable id: String, @RequestBody command: Command) = //... } data class Command(   val field1: String,   // ... )
 
Sidebar 里面看到识别到的 request body 成了：
 {   "id": "",   "command": "" }
 
对于有 response body 的 API，识别到的 response 也是空的。
 我们的 command  和 resopnse 都是用的 data class，controller 上的方法都是使用的表达式，没有写返回类型。
 
&mdash;

**Comment by kbyyd24** [comment]
嗯嗯，能根据 path 找到 controller 就可以了  😂
