### ISSUE TITLE
接口搜索不能联动右侧窗口

### ISSUE THREAD

**Issue by yihuishou** [ZhangYuanSheng1217/RestfulTool#50]
**Describe the bug**

使用快捷键 CTRL + ALT + / 搜索，无法联动右侧窗口
相当于右侧窗口搜索功能消失了

**Comment by ZhangYuanSheng1217** [comment]
右侧搜索：选中某个api，直接按键盘输入即可

**Comment by yihuishou** [comment]
是搜索右侧的 API
