### ISSUE TITLE
如何在右侧的API窗口搜索指定的API？

### ISSUE THREAD

**Issue by yihuishou** [ZhangYuanSheng1217/RestfulTool#51]
无论是快捷键还是使用窗口的搜索按钮都会跳转到对应的代码上，
但是右侧API窗口并不会跳转，不能在右侧窗口中找到想要的API

**Comment by ZhangYuanSheng1217** [comment]
直接双击就能跳转

**Comment by yihuishou** [comment]
双击可以从 API 窗口跳转到代码，但是代码双击并不能跳转右侧窗口中的 API

**Comment by ZhangYuanSheng1217** [comment]
这个不行的



---原始邮件---
发件人: "挥手的骑士"<notifications@github.com&gt;
发送时间: 2020年10月22日(周四) 上午10:55
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 如何在右侧的API窗口搜索指定的API？ (#51)




 
双击可以从 API 窗口跳转到代码，但是代码双击并不能跳转右侧窗口中的 API

**Comment by yihuishou** [comment]
希望右侧窗口能有个搜索功能，
在 API 很多的时候，可以快速查找 API 进行测试

**Comment by ZhangYuanSheng1217** [comment]
直接选中一个api输入要查的就行



---原始邮件---
发件人: "挥手的骑士"<notifications@github.com&gt;
发送时间: 2020年10月22日(周四) 中午11:04
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 如何在右侧的API窗口搜索指定的API？ (#51)




 
希望右侧窗口能有个搜索功能，
 在 API 很多的时候，可以快速查找 API 进行测试

**Comment by yihuishou** [comment]
右侧窗口选中一个 API 没看到输入的地方呢

**Comment by ZhangYuanSheng1217** [comment]
直接按字母键就行



---原始邮件---
发件人: "挥手的骑士"<notifications@github.com&gt;
发送时间: 2020年10月22日(周四) 中午11:09
收件人: "ZhangYuanSheng1217/RestfulTool"<RestfulTool@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Yuonsa"<2862297923@qq.com&gt;;
主题: Re: [ZhangYuanSheng1217/RestfulTool] 如何在右侧的API窗口搜索指定的API？ (#51)




 
右侧窗口选中一个 API 没看到输入的地方呢
