### ISSUE TITLE
提个建议吧

### ISSUE THREAD

**Issue by hopana** [ZhangYuanSheng1217/RestfulTool#9]
1、默认快捷键很容易冲突，而且没有地方改；我觉得老版Ctrl+\挺好的
2、@RequestMapping未指定GET或者POST的，这种既可以用POST又可以用GET的，别默认图标G，要么用R吧，区分开

**Comment by ZhangYuanSheng1217** [comment]
非常感谢您提出的问题
1、https://gitee.com/zys981029/RestfulTool/issues/I1HVP9
2、没有发现您所描述的情况，能否麻烦您给我看一下截图呢(*￣︶￣)

**Comment by Mystery00** [comment]
目前不支持 JAX-RS 吗，RestfulToolkit 是支持的，可惜没更新新版本，希望作者能加上对 JAX-RS 的支持

**Comment by ZhangYuanSheng1217** [comment]
已经提交了，请等待审核通过后更新(*￣︶￣)
