### ISSUE TITLE
HTTP请求端口号无法自动检测且设置默认端口号无效

### ISSUE THREAD

**Issue by AstroAbyss** [ZhangYuanSheng1217/RestfulTool#96]
作者是不再更新了吗都过去了一年了
![设置](https://user-images.githubusercontent.com/67324125/198874757-f5b3a6fc-5292-4329-bdc8-1a9c02612e00.png)
![界面](https://user-images.githubusercontent.com/67324125/198874759-fb4f33b3-d251-44b3-912b-6c9f5728aa83.png)

**Comment by Freedomisgood** [comment]
你使用的版本是2022么？

**Comment by huzhujiang2014** [comment]
+1 遇到了这个问题，请问作者是不更新了吗，有替代品吗

**Comment by AstroAbyss** [comment]
> 你使用的版本是2022么？

是的

**Comment by AstroAbyss** [comment]
> 你使用的版本是2022么？

是的
